export const dark = {
    backgroundTopStop : "#212121",
    backgroundBelowStop : "#1a1a1a",
    regularText : "#ffffff",
    regularContainer : "#333333",
    regularContainerBorder : "black",
    regularContainerShadow : "rgba(0, 0, 0, 0.35)",
    emphasizedText : "#333333",
    emphasizedContainer : "#fafafa",
    emphasizedContainerBorder : "#555761",
    emphasizedContainerShadow : "rgba(255, 255, 255, 0.35)",
    unselectedBareText : "#333333",
    aboutToBeSelectedBareText : "#4d4d4d",
    standaloneBorder : "#808080",
    scrollbarThumbFill : "#333333",
    scrollbarThumbBorder : "#000000",
    scrollbarThumbHoveredFill : "#666666",
    scrollbarThumbHoveredBorder : "#000000",
    scrollbarTrackFill : "rgba(0, 0, 0, 0)",
    scrollbarTrackBorder : "rgba(0, 0, 0, 0)",
    scrollbarTrackHoveredFill : "rgba(0, 0, 0, 0)",
    scrollbarTrackHoveredBorder : "rgba(0, 0, 0, 0)",
};

export const light = {
    backgroundTopStop : "#ffffff",
    backgroundBelowStop : "#d4d4d4",
    regularText : "#1a1a1a",
    regularContainer : "#d4d4d4",
    regularContainerBorder : "#abacae",
    regularContainerShadow : "rgba(0, 0, 0, 0.35)",
    emphasizedText : "#ffffff",
    emphasizedContainer : "#333333",
    emphasizedContainerBorder : "black",
    emphasizedContainerShadow : "rgba(0, 0, 0, 0.35)",
    unselectedBareText : "#95a3ab",
    standaloneBorder : "#000000",

};